const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 150,
    img: './images/item-1.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde explicabo harum exercitationem labore ea sed dolore vitae consectetur optio ipsa!`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis earum perspiciatis, vel asperiores cumque totam doloremque modi? Cumque, molestias nam.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 125,
    img: './images/item-3.jpeg',
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo nostrum nobis mollitia ut accusantium vero qui ipsam distinctio voluptatibus voluptas!`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 350,
    img: './images/item-4.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque corrupti est voluptatem magnam enim fugit exercitationem quaerat error porro explicabo.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 220,
    img: './images/item-5.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate sint dolor alias nihil amet dicta nobis, repudiandae eos?`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 130,
    img: './images/item-6.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, hic. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias eos omnis nihil.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 165,
    img: './images/item-7.jpeg',
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Distinctio rerum eligendi laboriosam architecto sed perferendis possimus laudantium error sequi asperiores tempora nobis ipsum ipsam cum, tenetur unde. Magni, quam beatae!`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 350,
    img: './images/item-8.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus libero sequi, consequuntur odio consequatur nihil quaerat vitae suscipit magnam nisi? Culpa autem laboriosam ipsum!`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 150,
    img: './images/item-9.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo ut tempore nulla, adipisci libero beatae illo suscipit?`,
  },
]
export default menu
